working_dirs:
  - C:\Users\Noxware\Desktop\prueba

decisions:
  Tiene gatito:
    Chikito: C:\Users\Noxware\Desktop\prueba/o/Gatitos/Chikitos
    Gordito: C:\Users\Noxware\Desktop\prueba/o/Gatitos/Gorditos
  Tiene perrito: C:\Users\Noxware\Desktop\prueba/o/Perritos
  Otro:
    _directory: C:\Users\Noxware\Desktop\prueba/o/Otros
