vars:
  other: C:\Users\Noxware\Desktop\prueba/o2

working_dirs:
  - C:\Users\Noxware\Desktop\prueba
  - C:\Users\Noxware\Desktop\prueba\Flattened

decisions:
  Tiene gatito:
    Chikito: C:\Users\Noxware\Desktop\prueba/o/Gatitos/Chikitos
    Gordito: C:\Users\Noxware\Desktop\prueba/o/Gatitos/Gorditos
  Tiene perrito: C:\Users\Noxware\Desktop\prueba/o/Perritos
  Otro:
    _directory: $other/Otros
